from abc import ABCMeta, abstractmethod

from EventDriven.helpers import generate_signal_id

from EventDriven.event import SignalEvent
from trade.helpers.Logging import setup_logger

class Strategy(object):
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars 
    (OLHCVI) generated by a DataHandler object.

    This is designed to work both with historic and live data as
    the Strategy object is agnostic to the data source,
    since it obtains the bar tuples from a queue object.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def calculate_signals(self):
        """
        Provides the mechanisms to calculate the list of signals.
        """
        raise NotImplementedError("Should implement calculate_signals()")
    
    
    

class BuyAndHoldStrategy(Strategy):
    """
    This is an extremely simple strategy that goes LONG all of the 
    symbols as soon as a bar is received. It will never exit a position.

    It is primarily used as a testing mechanism for the Strategy class
    as well as a benchmark upon which to compare other strategies.
    """

    def __init__(self, bars, events):
        """
        Initialises the buy and hold strategy.

        Parameters:
        bars - The DataHandler object that provides bar information
        events - The Event Queue object.
        """
        self.bars = bars
        self.symbol_list = self.bars.symbol_list
        self.events = events

        # Once buy & hold signal is given, these are set to True
        self.bought = self._calculate_initial_bought()
        
    def _calculate_initial_bought(self):
        """
        Adds keys to the bought dictionary for all symbols
        and sets them to False.
        """
        bought = {}
        for s in self.symbol_list:
            bought[s] = False
        return bought

    def calculate_signals(self, event):
        """
        For "Buy and Hold" we generate a single signal per symbol
        and then no additional signals. This means we are 
        constantly long the market from the date of strategy
        initialisation.

        Parameters
        event - A MarketEvent object. 
        """
        if event.type == 'MARKET':
            for s in self.symbol_list:
                bars = self.bars.get_latest_bars(s, N=1)
                if bars is not None and bars != []:
                    if self.bought[s] == False:
                        # (Symbol, Datetime, Type = LONG, SHORT or EXIT)
                        signal = SignalEvent(bars[0][0], bars[0][1], 'LONG')
                        self.events.put(signal)
                        self.bought[s] = True
                        
                        
                        
class OptionSignalStrategy(Strategy): 
    """
    Ths is a simple strategy that generates a signal to buy or sell options based on data from the data handler.
    """
    
    def __init__(self, bars, events):
        self.bars = bars
        self.events = events
        self.symbol_list = self.bars.symbol_list
        self.logger = setup_logger('OptionSignalStrategy')

    def calculate_signals(self): 
        """
            For signal reading, we read a dataframe row for 1, -1 or 0 to signify the following:
            1: Buy option
            -1: Sell option
            0: Do nothing
        """
        self.__latest_signals = self.bars.get_latest_bars('') #this returns a dataframe with the latest signals for each underlier
        latest_signals_row = self.__latest_signals.iloc[0]
        date = latest_signals_row['Date']
        
        for underlier in self.symbol_list:
            signal_value = latest_signals_row[underlier]
            if signal_value == 1:
                signal = SignalEvent(underlier, date, 'LONG', generate_signal_id(underlier, date, 'LONG'))
                self.logger.info(f"LONG Signal for {underlier} at {date}")
                self.events.put(signal)
            elif signal_value == -1:
                signal = SignalEvent(underlier, date, 'CLOSE')
                self.logger.info(f"CLOSE Signal for {underlier} at {date}")
                self.events.put(signal)
            elif signal_value == 2:
                signal = SignalEvent(underlier, date, 'SHORT', generate_signal_id(underlier, date, 'SHORT')) 
                self.logger.info(f"SHORT Signal for {underlier} at {date}")
                self.events.put(signal)
            else: 
                self.logger.info(f"No signal for {underlier} at {date}")
          
        