from typing import TypedDict
from enum import Enum

class ResultsEnum(Enum):
    SUCCESSFUL = 'SUCCESSFUL'
    MONEYNESS_TOO_TIGHT = 'MONEYNESS_TOO_TIGHT'
    NO_ORDERS = 'NO_ORDERS'
    UNSUCCESSFUL = 'UNSUCCESSFUL'
    IS_HOLIDAY = 'IS_HOLIDAY'
    UNAVAILABLE_CONTRACT = 'NO LISTED CONTRACTS' 
    MAX_PRICE_TOO_LOW = 'MAX_PRICE_TOO_LOW'
    TOO_ILLIQUID = 'TOO_ILLIQUID'
    NO_TRADED_CLOSE = 'NO_TRADED_CLOSE'
    IS_WEEKEND = 'IS_WEEKEND'
    
class EventTypes(Enum): 
  SIGNAL = 'SIGNAL'
  ORDER = 'ORDER'
  FILL = 'FILL'
  MARKET = 'MARKET'
  EXERCISE = 'EXERCISE'
  
class SignalTypes(Enum):
  LONG = 'LONG'
  SHORT = 'SHORT'
  CLOSE = 'CLOSE'